### ISSUE TITLE
checkbox

### ISSUE THREAD

**Issue by MaskDuck** [is-a-dev/register.is-a.dev#51]
register manually requires a checkbox, can we also implement it in the app thx

**Comment by WilliamDavidHarrison** [comment]
Why tf did you assign me

**Comment by WilliamDavidHarrison** [comment]
We'll implement it

**Comment by WilliamDavidHarrison** [comment]
> why aren't you implementing it, but "will"?

I don't work on the register site really, and I'm working on other projects atm.

**Comment by WilliamDavidHarrison** [comment]
@andrewstech Might be able to as I don't know the codebase that well. If I get time I will add it.

**Comment by andrewstech** [comment]
So you want a checkbox to say something along the lines of "Website completed and accessable"?

@MaskDuck

**Comment by andrewstech** [comment]
ok

**Comment by daanschenkel** [comment]
Can this be closed?
