### ISSUE TITLE
Unable to register through UI

### ISSUE THREAD

**Issue by sangramrath** [is-a-dev/register.is-a.dev#75]
Hi, on a recent attempt to register a subdomain, it failed to login. I am unsure of its default behavior as this is the first time I am checking it out. After approving the sign-in it continued to remain in the same page. It did show it was redirecting to auth.is-a.dev. Attached is an error screenshot.

![Screenshot 2023-02-22 at 6 55 47 PM](https://user-images.githubusercontent.com/6134395/220633105-bf89b53c-9a79-45dd-9c6a-4bd775aace48.png)

**Comment by WilliamDavidHarrison** [comment]
@andrewstech

**Comment by andrewstech** [comment]
Due to the amount of bugs I have taken the decision to take down the site at this time. I'm currently working on a Full rewrite that I hope to release by the end of the week
